# -*- coding: utf-8 -*-
"""[CSCI 113] Group Capstone Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTrDyKFJvw5N9fmxdLVZkL2fOHbghdIz

# **Importing Dataset**
"""

# Required libraries
!pip install catboost
!pip install scikit-learn
!pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns

# Models
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# Load datasets
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv'
df = pd.read_csv(url, sep=';')

url2 = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
df2 = pd.read_csv(url2, sep=';')

# Add wine type
df2['wine_type'] = 'red'
df['wine_type'] = 'white'

# Merge
wine = pd.concat([df2, df], axis=0, ignore_index=True)

# Drop wine_type column entirely (do not use it as a feature)
wine.drop('wine_type', axis=1, inplace=True)

# Define features and target
X = wine.drop('quality', axis=1)
y = wine['quality']

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# **Histograms per Independent Variable**"""

wine.hist(figsize=(15, 12), bins=30, edgecolor='black')

plt.suptitle("Histograms of Wine Quality Features", fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

"""## **Correlation Matrix & Heatmap**"""

corr_matrix = wine.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", square=True)
plt.title("Correlation Heatmap of Wine Features")
plt.show()

"""## **Scatter Plots (All Variables vs. Quality)**"""

independent_vars = [col for col in wine.columns if col != 'quality']

for col in independent_vars:
    plt.figure(figsize=(6, 4))
    sns.scatterplot(x=col, y='quality', data=df, alpha=0.6)
    plt.title(f"{col} vs Quality")
    plt.xlabel(col)
    plt.ylabel("Quality")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

"""## **Pairwise Scatterplots**"""

numeric_df = wine.select_dtypes(include=['number'])

sns.pairplot(numeric_df)
plt.show()